
spring:
  application:
    name: practice-service
  data:
    mongodb:
      host: rc1a-iaj8kf6jaomgk9lf.mdb.yandexcloud.net
      port: 27018
      password: goeasypractice
      username: practice-service
      database: practice-service
      authentication-database: practice-service

server:
  error:
    include-message: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html